drop table Student if exists;
create table Student(
student_id integer generated by default as identity, 
student_name varchar(255), 
student_email varchar(255), 
student_branck varchar(255), 
primary key (student_id));